### ISSUE TITLE
Duplicate Trigger method

### ISSUE THREAD

**Issue by tachiniererin** [litao91/goldmark-mathjax#3]
The last PR implemented a new .Trigger method: https://github.com/litao91/goldmark-mathjax/blob/e57dec9a1d876ad391bdfd1a9a78134b5bb69336/block.go#L25 but the old one wasn't removed: https://github.com/litao91/goldmark-mathjax/blob/e57dec9a1d876ad391bdfd1a9a78134b5bb69336/block.go#L80 which means it doesn't compile anymore now.

**Comment by athul** [comment]
I had made a fork of this and removed the redundant code.
You can run `go get github.com/athul/goldmark-mathjax`.

 I'll send a PR soon on this
